/**
 * TWDB reservoir key -> URL slug.
 *
 * GENERATED FILE — do not edit by hand. Run `npm run sync:slugs` to refresh.
 *
 * TWDB's JSON feed keys reservoirs by condensed name ("BASteinhagen") while its
 * CSV endpoints use a different slug ("b-a-steinhagen"), and the transform is not
 * mechanically derivable (compare "bois-darc"). This map is produced by matching
 * both sources on their alphanumeric-only forms.
 */
export const RESERVOIR_SLUGS: Record<string, string> = {
  "Abilene": "abilene",
  "Addicks": "addicks",
  "AlanHenry": "alan-henry",
  "Amistad": "amistad",
  "AmonGCarter": "amon-g-carter",
  "Aquilla": "aquilla",
  "Arlington": "arlington",
  "Arrowhead": "arrowhead",
  "Athens": "athens",
  "Austin": "austin",
  "Bardwell": "bardwell",
  "Barker": "barker",
  "BASteinhagen": "b-a-steinhagen",
  "Belton": "belton",
  "Benbrook": "benbrook",
  "BobSandlin": "bob-sandlin",
  "BoisDArc": "bois-darc",
  "Bonham": "bonham",
  "BradyCreek": "brady-creek",
  "Bridgeport": "bridgeport",
  "Brownwood": "brownwood",
  "Buchanan": "buchanan",
  "Caddo": "caddo",
  "Canyon": "canyon",
  "CedarCreek": "cedar-creek",
  "ChampionCreek": "champion-creek",
  "Cherokee": "cherokee",
  "ChokeCanyon": "choke-canyon",
  "Cisco": "cisco",
  "Coleman": "coleman",
  "ColetoCreek": "coleto-creek",
  "ColoradoCity": "colorado-city",
  "ComancheCreek": "comanche-creek",
  "Conroe": "conroe",
  "CorpusChristi": "corpus-christi",
  "Crook": "crook",
  "CypressSprings": "cypress-springs",
  "EagleMountain": "eagle-mountain",
  "ElephantButte": "elephant-butte",
  "EVSpence": "e-v-spence",
  "Falcon": "falcon",
  "Fork": "fork",
  "FortPhantomHill": "fort-phantom-hill",
  "Georgetown": "georgetown",
  "GibbonsCreek": "gibbons-creek",
  "Graham": "graham",
  "Granbury": "granbury",
  "Granger": "granger",
  "Grapevine": "grapevine",
  "Greenbelt": "greenbelt",
  "Halbert": "halbert",
  "HordsCreek": "hords-creek",
  "Houston": "houston",
  "HoustonCounty": "houston-county",
  "HubbardCreek": "hubbard-creek",
  "HubertHMoss": "hubert-h-moss",
  "Inks": "inks",
  "Jacksonville": "jacksonville",
  "JBThomas": "j-b-thomas",
  "JimChapman": "jim-chapman",
  "JoePool": "joe-pool",
  "Kemp": "kemp",
  "Kickapoo": "kickapoo",
  "Lake O' the Pines": "lake-o-the-pines",
  "Lavon": "lavon",
  "Leon": "leon",
  "Lewisville": "lewisville",
  "Limestone": "limestone",
  "Livingston": "livingston",
  "LostCreek": "lost-creek",
  "LyndonBJohnson": "lyndon-b-johnson",
  "Mackenzie": "mackenzie",
  "MarbleFalls": "marble-falls",
  "Martin": "martin",
  "Medina": "medina",
  "Meredith": "meredith",
  "MillersCreek": "millers-creek",
  "MineralWells": "mineral-wells",
  "Monticello": "monticello",
  "MountainCreek": "mountain-creek",
  "Murvaul": "murvaul",
  "Nacogdoches": "nacogdoches",
  "Nasworthy": "nasworthy",
  "NavarroMills": "navarro-mills",
  "NewTerrellCity": "new-terrell-city",
  "Nocona": "nocona",
  "NorthForkBuffaloCreek": "north-fork-buffalo-creek",
  "OakCreek": "oak-creek",
  "OCFisher": "o-c-fisher",
  "OHIvie": "o-h-ivie",
  "Palestine": "palestine",
  "PaloDuro": "palo-duro",
  "PaloPinto": "palo-pinto",
  "PatCleburne": "pat-cleburne",
  "PatMayse": "pat-mayse",
  "PossumKingdom": "possum-kingdom",
  "Proctor": "proctor",
  "RayHubbard": "ray-hubbard",
  "RayRoberts": "ray-roberts",
  "RedBluff": "red-bluff",
  "RichlandChambers": "richland-chambers",
  "SamRayburn": "sam-rayburn",
  "Somerville": "somerville",
  "Stamford": "stamford",
  "StillhouseHollow": "stillhouse-hollow",
  "Striker": "striker",
  "SulphurSprings": "sulphur-springs",
  "Sweetwater": "sweetwater",
  "Tawakoni": "tawakoni",
  "Texana": "texana",
  "Texoma": "texoma",
  "ToledoBend": "toledo-bend",
  "Travis": "travis",
  "TwinButtes": "twin-buttes",
  "Tyler": "tyler",
  "Waco": "waco",
  "Waxahachie": "waxahachie",
  "Weatherford": "weatherford",
  "WhiteRiver": "white-river",
  "Whitney": "whitney",
  "Worth": "worth",
  "WrightPatman": "wright-patman",
};

export const ALL_SLUGS = Object.values(RESERVOIR_SLUGS);
